### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by vict0rsch** [wwMark/meshgraphnets#1]
Hi @wwMark,

I was looking for a Pytorch implementation of the MeshGraphNets and I stumbled upon your repo. 

Judging on the commits and the state of `requirements.txt` I expect this is very much work in progress?

Do you already know what is functional or not (if it's not all functional)?

Thanks for sharing this work,

Victor

**Comment by wwMark** [comment]
> Hi @wwMark,
> 
> I was looking for a Pytorch implementation of the MeshGraphNets and I stumbled upon your repo.
> 
> Judging on the commits and the state of `requirements.txt` I expect this is very much work in progress?
> 
> Do you already know what is functional or not (if it's not all functional)?
> 
> Thanks for sharing this work,
> 
> Victor

Hi Victor,

my code in main branch works on both linux and windows for the cloth simulation, and the cfd simulation code is not ported to pytorch, though it is quite similar with the cloth simulation code and should be easily ported to torch taking the cloth simulation code as reference.

Regards,
Mark

**Comment by vict0rsch** [comment]
Ok great to know thanks a lot :) 

(may I just suggest you update `requirements.txt`?)

**Comment by vict0rsch** [comment]
Also, do you plan on completely removing the tensorflow dependency?

**Comment by wwMark** [comment]
> Ok great to know thanks a lot :)
> 
> (may I just suggest you update `requirements.txt`?)

Hi Victor,

the requirements.txt is updated. Please give me feedback if it does not work. :)

**Comment by vict0rsch** [comment]
Thank you for updating the requirements. I could not install `torch-geometric` easily so after some time online I found this issue: 

and did this 

```
conda install pytorch==1.8.1 torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
pip install torch
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html    
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html
pip install torch-geometric
```

(writing for the Future :p )

**Comment by wwMark** [comment]
Thanks for the information Victor!

**Comment by yhl48** [comment]
> my code in main branch works on both linux and windows for the cloth simulation, and the cfd simulation code is not ported to pytorch, though it is quite similar with the cloth simulation code and should be easily ported to torch taking the cloth simulation code as reference.

Hi, which file should I modify to run cfd simulation with pytorch?

**Comment by wwMark** [comment]
Hi Lim,

the README is behind the current status of the repo and now the cfd
simulation is already implemented in pytorch, you can run it by modifying
line 57 of run_model.py.

Best regards
Mark

**Comment by yhl48** [comment]
@wwMark Hi mark, I realised that after raising the question, really appreciate it! Thank you for sharing the repository!
