### ISSUE TITLE
bug in _update_node_features

### ISSUE THREAD

**Issue by ligengen** [wwMark/meshgraphnets#3]
Hi, the updated feature is not added into **features**
https://github.com/wwMark/meshgraphnets/blob/55bdeb02f99d4213f72d0ff444288544455b9611/core_model.py#L54

**Comment by wwMark** [comment]
Hi @ligengen,

the core_model.py is actually aborted in the work and will be deleted later. The functioning core model is the .py files starting with encode_process_decode. Please check these files.

Regards
Mark

**Comment by ligengen** [comment]
Thank you and I'll check later
